name: sample_project
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State manager, provider  
  flutter_riverpod: ^2.0.0-dev.9

  # Http
  dio: ^4.0.6

  # Navigation
  go_router: ^4.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  auto_route_generator: ^5.0.1
  build_runner: ^2.2.0  

  flutter_lints: ^2.0.0

  # Launcher icons
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/2.0x/logo.png"
  web:
    image_path: "assets/images/2.0x/logo.png"
    generate: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/2.0x/
    - assets/images/profile/
    - assets/images/pics/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
